title:             기술 블로그
email:             jhd9206@gmail.com
description:       제가 공부한 기술을 기록하는 블로그입니다. 틀린 점이나 다른 생각들에 대한 피드백은 메일로 부탁드리면 감사하겠습니다.
author:            hodongman
baseurl:           "/"
url:               "https://hodongman.github.io"

# Social Profiles
twitter_username:  hodongman
github_username:   hodongman
facebook_username: hodongman

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
